import type { OntologyConcept } from './types.js';

export const ontologyConcepts: readonly OntologyConcept[] = [
  {
    id: 'intelligent_infinity',
    name: 'Intelligent Infinity',
    shortDescription: 'Undifferentiated unity and infinite potential within the Ra ontology.',
    classification: 'SOURCE_BACKED',
    parentIds: [],
    childIds: ['free_will'],
    sourceRecordIds: ['source-intelligent-infinity'],
  },
  {
    id: 'free_will',
    name: 'Free Will',
    shortDescription: 'The First Distortion; the opening for the Creator to know Itself through experience.',
    classification: 'SOURCE_BACKED',
    parentIds: ['intelligent_infinity'],
    childIds: ['logos_love'],
    sourceRecordIds: ['source-primal-distortions'],
  },
  {
    id: 'logos_love',
    name: 'Love / Logos',
    shortDescription: 'The Second Distortion; the creative focusing principle.',
    classification: 'SOURCE_BACKED',
    parentIds: ['free_will'],
    childIds: ['light'],
    sourceRecordIds: ['source-primal-distortions'],
  },
  {
    id: 'light',
    name: 'Light',
    shortDescription: 'The Third Distortion; manifestation and the building block of matter within the model.',
    classification: 'SOURCE_BACKED',
    parentIds: ['logos_love'],
    childIds: ['creation'],
    sourceRecordIds: ['source-primal-distortions', 'source-cosmogenesis'],
  },
  {
    id: 'creation',
    name: 'Creation',
    shortDescription: 'Local rhythms, fields, dimensions, and universes emerging from intelligent energy.',
    classification: 'SOURCE_BACKED',
    parentIds: ['light'],
    childIds: ['density'],
    sourceRecordIds: ['source-cosmogenesis'],
  },
  {
    id: 'density',
    name: 'Densities',
    shortDescription: 'Sequential qualitative environments of experience, not simple spatial floors.',
    classification: 'SOURCE_BACKED',
    parentIds: ['creation'],
    childIds: ['mind_body_spirit_complex'],
    sourceRecordIds: ['source-density-overview'],
  },
  {
    id: 'mind_body_spirit_complex',
    name: 'Mind/Body/Spirit Complex',
    shortDescription: 'The integrated entity through which experience is processed.',
    classification: 'SOURCE_BACKED',
    parentIds: ['density'],
    childIds: ['catalyst', 'polarity', 'higher_self'],
    sourceRecordIds: ['source-energy-centers'],
  },
  {
    id: 'catalyst',
    name: 'Catalyst',
    shortDescription: 'Experience entering awareness and becoming material for learning, balancing, and choice.',
    classification: 'SOURCE_BACKED',
    parentIds: ['mind_body_spirit_complex'],
    childIds: ['polarity'],
    sourceRecordIds: ['source-catalyst'],
  },
  {
    id: 'polarity',
    name: 'Polarity',
    shortDescription: 'The third-density orientation toward service to others or service to self.',
    classification: 'SOURCE_BACKED',
    parentIds: ['catalyst'],
    childIds: ['harvest'],
    sourceRecordIds: ['source-harvest-thresholds'],
  },
  {
    id: 'harvest',
    name: 'Harvest',
    shortDescription: 'Transition by vibrational compatibility rather than external judgment.',
    classification: 'SOURCE_BACKED',
    parentIds: ['polarity'],
    childIds: ['social_memory_complex'],
    sourceRecordIds: ['source-harvest-resonance', 'source-harvest-thresholds'],
  },
  {
    id: 'higher_self',
    name: 'Higher Self',
    shortDescription: 'A resource for healing and further life programming while preserving free choice.',
    classification: 'SOURCE_BACKED',
    parentIds: ['mind_body_spirit_complex'],
    childIds: ['time_space'],
    sourceRecordIds: ['source-higher-self'],
  },
  {
    id: 'social_memory_complex',
    name: 'Social Memory Complex',
    shortDescription: 'Many unique entities sharing memory and understanding through a collective field.',
    classification: 'SOURCE_BACKED',
    parentIds: ['harvest'],
    childIds: [],
    sourceRecordIds: ['source-social-memory'],
  },
  {
    id: 'space_time',
    name: 'Space/Time',
    shortDescription: 'The incarnate physical arena of sequential experience.',
    classification: 'SOURCE_BACKED',
    parentIds: [],
    childIds: ['time_space'],
    sourceRecordIds: ['source-space-time-time-space'],
  },
  {
    id: 'time_space',
    name: 'Time/Space',
    shortDescription: 'The metaphysical counterpart used in the material for review, healing, and non-ordinary temporal relations.',
    classification: 'SOURCE_BACKED',
    parentIds: ['space_time', 'higher_self'],
    childIds: [],
    sourceRecordIds: ['source-space-time-time-space', 'source-higher-self'],
  },
] as const;
