import type { SourceRecord } from '../types.js';

export const phase3Sources: readonly SourceRecord[] = [
  { id: 'source-totality', conceptId: 'totality', title: 'Mind/Body/Spirit Totality', classification: 'SOURCE_BACKED', summary: 'Ra describes Totality as a resource available to Higher Self, including parallel developments.', references: [{ session: 36, question: '1-2', note: 'Totality and the information used by Higher Self.' }], implementationNote: 'Layered ribbons are an information metaphor, not the shape of Totality.' },
  { id: 'source-vortices', conceptId: 'possibility_vortices', title: 'Probability / possibility vortices', classification: 'SOURCE_BACKED', summary: 'Possibility information can inform further life programming.', references: [{ session: 36, question: 2, note: 'Projected probability/possibility vortices.' }], implementationNote: 'The graph is finite and illustrative. Its weights do not estimate real futures.' },
  { id: 'source-programming', conceptId: 'incarnation_program', title: 'Lessons and predispositions', classification: 'SOURCE_BACKED', summary: 'Lessons and some predispositions may be programmed; responses remain the entity’s choice.', references: [{ session: 36, question: 7, note: 'The map relationship and the authority of free choice.' }, { session: 21, question: '9-10', note: 'Participation in incarnation conditions develops over time.' }], implementationNote: 'The seven configurable fields and all preset examples are simulation abstractions.' },
  { id: 'source-program-conditions', conceptId: 'program_conditions', title: 'A model of conditions', classification: 'INFERRED', summary: 'The planning interface relates lessons, relationships, and circumstances as possible learning conditions.', references: [{ session: 36, question: 7, note: 'Lessons and predisposing limitations.' }, { session: 21, question: 10, note: 'Choosing parents in the context of non-automatic incarnation.' }], implementationNote: 'Specific presets are invented examples. A condition never assigns a response; adversity is not evidence of a chosen lesson.' },
  { id: 'source-form-maker', conceptId: 'form_maker', title: 'Indigo / form-maker transition', classification: 'SOURCE_BACKED', summary: 'Ra identifies the indigo body as the first activated after physical death and describes it as a perspective for reviewing experience and preparing for incarnation.', references: [{ session: 47, question: '11-15', note: 'Activation and preparation; the passage describes variations, not a rigid timetable.' }], implementationNote: 'The dissolving trajectory and transition duration are visual abstractions. This is not a claim about an observed process.' },
  { id: 'source-life-review', conceptId: 'life_review', title: 'Review between incarnations', classification: 'SOURCE_BACKED', summary: 'Ra describes increasing attention to reviewing and healing experience between incarnations.', references: [{ session: 21, question: 9, note: 'The account distinguishes early automatic incarnation from later participation.' }, { session: 47, question: 15, note: 'A perspective on the experience just completed.' }], implementationNote: 'Grouping recorded events by lesson or response is a simulation abstraction; there is no moral score.' },
  { id: 'source-healing', conceptId: 'healing', title: 'Assistance with integration', classification: 'SOURCE_BACKED', summary: 'Higher Self is described as assisting healing and further programming.', references: [{ session: 36, question: 2, note: 'Healing and further experience.' }], implementationNote: 'Marking an event as integrated is a user annotation, not a diagnosis or a measurement of spiritual healing.' },
  { id: 'source-veil', conceptId: 'veil', title: 'Limited incarnate perspective', classification: 'SOURCE_BACKED', summary: 'Ra relates third-density forgetting to the conditions in which free choice operates.', references: [{ session: 21, question: 9, note: 'Forgetting and the development of experience.' }], implementationNote: 'Hiding distant nodes is a UI metaphor. Changing the viewing lens does not represent attaining metaphysical knowledge.' },
  { id: 'source-visual-weights', conceptId: 'visual_weights', title: 'Branch geometry and visual weights', classification: 'SIMULATION_ABSTRACTION', summary: 'Splines, branch statuses, bounded weights, timing, colors, camera placement, and illustrative consequences are authored simulation mechanics.', references: [], implementationNote: 'Weights are independent visual emphasis values from 0 to 1. They are not probabilities and need not sum to one.' },
  { id: 'source-perspective-lenses', conceptId: 'perspective_lenses', title: 'Three information lenses', classification: 'SIMULATION_ABSTRACTION', summary: 'The incarnate, Higher Self, and Totality lenses reveal progressively more of the same recorded experience and illustrative possibilities.', references: [{ session: 36, question: '1-7', note: 'Conceptual motivation for the lenses; their interface and layout are not stated in the text.' }], implementationNote: 'A lens changes visibility only. It does not change identity, create life events, or authorize a response.' },
];
